### ISSUE TITLE
End of experiment message

### ISSUE THREAD

**Issue by Sharonii** [lutzky/seaplane#3]
כאשר מסתיימים כל צעדי הניסוי מופיעה הודעה:
הניסוי הסתיים.
תודה על השתתפותך! 
בדרך כלל בשלב הזה התוכנה ממש נסגרת ו"זורקת" את הנבדק החוצה, כאשר עבור כל נבדק חדש נהוג לפתוח אותה מחדש... אבל אם זה מסובך - אז התוכנה יכולה להישאר תקועה על ההודעה הזאת או משהו.

**Comment by lutzky** [comment]
The easiest thing for me to implement would be staying stuck on that message, so you'd hit "refresh" to get a fresh experiment. However, this means that the downloadable TSV file will be cleared out as well. Is that good for you?

**Comment by Sharonii** [comment]
זה נשמע לי ממש לא בטיחותי שכל המידע ילך לאיבוד בכזאת קלות... 
ואם אני בטעות שוכחת ללחוץ על החץ? או שהנבדק נוגע במשהו במקלדת בטעות? זה די מפחיד אותי. 
אפשר איכשהו שתהיה הפרדה מוחלטת בין הניסויים ושמירה אוטומטית של השינויים, או שזה ממש קשה לביצוע?..

**Comment by lutzky** [comment]
זה כבר ממש קשה לביצוע. חלק גדול מהסיבה שהפרוייקט הזה קל יחסית הוא שהכל קורה בתוך הדפדפן, ואני לא מחזיק שום דבר דינמי בשרת.
מה אם ה"תודה על השתתפותך" יהיה גם לינק להורדה?
אולי אחרי שה"תודה על השתתפותך" מופיע אני אפעיל אוטומטית את ההורדה?

**Comment by Sharonii** [comment]
כלומר, ברגע שיסתיימו כל הטרייליים (צעדים) ותופיעה ההודעה הנתונים שלהם ירדו אוטומטית? זה נשמע לי רעיון מצוין. ככה זה בטוח ירד ובטוח יישמר, לא משנה על מה הנבדק לחץ או האם הנסיין זכר או לא זכר ללחוץ על כפתור החץ...

**Comment by lutzky** [comment]
OK, auto-downloading seems to work appropriately.
To test this out without waiting for 264 stages, you can open the Javascript Console (hit F12) and type:

``` javascript
seaplane.currentStage = 260
```
