### ISSUE TITLE
Import word changes from config. file

### ISSUE THREAD

**Issue by Sharonii** [lutzky/seaplane#4]
היי, מותק!
אז ערכתי את כל המילים, אבל נאלצתי לחזור לקובץ הקונפיג, כיוון שהעריכה כאן ממש קשה לי (הכל מתהפך). אז אני לא רואה היכן יש כאן אפשרות לצרף קובץ, אז אשלח לך במייל ורק תאחד אותם.

**Comment by lutzky** [comment]
I just edited the file and copied and pasted from your file. It seems to have worked.
