### ISSUE TITLE
Add an opening message & a practice block

### ISSUE THREAD

**Issue by Sharonii** [lutzky/seaplane#5]
בחילת הניסוי צריכה להופיעה הודעה בסגנון: 
שלום, 
הנך עומד להשתתף בניסוי שמטרתו לבדוק כך וכך...
עליך למקד את מבטך במרכז המסך לאורך הניסוי כולו. במרכז המסך יופיעו צלב ולאחריו מילה שתוצג למשך זמן קצר. לאחר מכן בחלקו העליון או בחלקו התחתון של המסך יופיע גירוי המטרה.
 עליך להגיב בלחיצה על מקש הרווח (space) ברגע שהנך מבחין במטרה, הכי מהר ומדויק שאתם יכולים. 
שים לב שהמילים אינן מנבאות את הופעת המטרה במיקום כלשהו. 
אנחנו מודים לך על שיתוף הפעולה!
להתחלת הניסוי לחץ על מקש מקש כלשהו

לאחר העמוד הזה יופיע עמוד נוסף ובו כתוב:
שלב האימון 
לחץ על מקש כלשהו כדי להתחיל

ואחר כך שלב האימון מתחיל ושם אני צריכה שיהיה לי מקום להזין את 10 המילים הנייטרליות הנוספות.
הדבר הזה לא צריך להופיע בפלט, ואם הוא מופיע - אז שיהיה מופרד איכשהו מהנתונים הרלוונטיים. 
3-4 וגם שם צריכים להיות catch trials.

**Comment by lutzky** [comment]
I need some more details on how the practice phase works - how long is it? How many (exactly or probabilities) words of each category do you want?

**Comment by lutzky** [comment]
It's currently implemented the same way as the main experiment - for each word in `WORDS.practice`, 4 stages will be made - two up, two down. In additional, `CATCH_TRIALS_PRACTICE` will be selected out of those. So that's 43 stages in total for the practice portion. If this is inappropriate, please reopen.

**Comment by Sharonii** [comment]
אז ככה, צריך בסה"כ 10 מילים חדשות. אני מצטערת אם זה לא מובן, אבל זה גם אומר בדיוק 10 צעדים עד שמתחיל הניסוי האמיתי. המטרה היא לא באמת לאמן את הנבדקים להגיב, אלא לערוך להם היכרות עם מבנה הניסוי כדי שכשהוא יתחיל הצעדים הראשונים לא יתבזבזו על הניסיון להבין מה לעשות... 
ראיתי שהכנת בקובץ הקונפיג את הפלטפורמה בשביל שאכניס שם את המילים שצריך, ואני כבר יודעת איך לעשות את זה. 
מבחינת ההסתברויות - מתוך ה-10 מילים צריך 3-4 קאצ' טריילס, אז שיהיה חצי למעלה וחצי למטה. המילים הן בכל מקרה בעלות משמעות נייטרלית מבחינת אוריינטציה מרחבית, ואלה הן מילים חדשות שלא יופיעו בניסוי האמיתי.

**Comment by lutzky** [comment]
3 up
4 down
3 catch trials
