### ISSUE TITLE
Insert ISI (Inter-stimulus interval)

### ISSUE THREAD

**Issue by Sharonii** [lutzky/seaplane#6]
אני לא יודעת אם כבר עשית את זה, אבל אני לא רואה את זה בקונפיג...
בכל אופן, בין סוף הצגת המילה לבין הצגת גירוי המטרה צריכות לעבור 50 מילישניות. כלומר, מתחילת הצגת המילה ועד להופעת הגירוי - 300 מילישניות בסה"כ.

**Comment by lutzky** [comment]
50ms is very short and can barely be noticed, but you're the doc, doc :stuck_out_tongue_winking_eye:.  During testing I had to bump it up to 500ms to make sure it was working correctly.

**Comment by Sharonii** [comment]
זה נכון מה שאתה אומר, זה קצר בטירוף... אבל המרצה שלי אמרה שזה נשמע לה בסדר, אז מקסימום, כשהיא תראה את הניסוי היא תגיד לי להעלות את זה קצת. זה כבר באמת זניח. אבל תודה, בייב! <3
