### ISSUE TITLE
Verify that TSV output format is appropriate

### ISSUE THREAD

**Issue by lutzky** [lutzky/seaplane#8]
Make sure that the current version of the TSV output (especially since #7 is fixed) is appropriate for import in whatever analysis tools you'll want to use.

**Comment by Sharonii** [comment]
היי, מותק!
 נראה לי שעניתי לך על זה, אבל במקום הלא נכון (בנושאים שכבר סגרת). בכל אופן, פתחתי את הקובץ עכשיו גם עם האס.פי.אס.אס וזה עובד מצוין. 
רק בקשה קטנה: האם אפשר לשנות את הערך המסמל את "לא הופיע גירוי" מ-3 ל-0? האס.פי.אס.אס מעדיף את זה ככה. 

לא משנה, הצלחתי לבד! (גאווה). תודה, בייב!

**Comment by lutzky** [comment]
Awesome :+1:! See, told you coding is fun :grin: (...when stuff works...)
A few notes:
- Note that you've also changed the numbering for the "neutral category" - it is now no longer 3, but rather 0. If this is inappropriate, please change `seaplane.js:233`.
- Please write appropriate commit messages - you can see now the commit history has "Update seaplane.js" with no rhyme nor reason.
- In your full commit description (not the title) you can write something like "Fixes #8" (the number of this issue) which will automatically close it. Alternatively, you can close it from the issue page, e.g. when writing a comment, as I'm doing now.
